export type ContentField = {
  key: string;
  label: string;
  multiline?: boolean;
  type?: 'text' | 'image';
  fallback: string;
};

export type ContentSection = {
  id: string;
  title: string;
  fields: ContentField[];
};

export type ContentPage = {
  id: string;
  title: string;
  sections: ContentSection[];
};

const makeInfoPage = (id: string, title: string, slug: string, defaultTitle: string, defaultSubtitle: string): ContentPage => ({
  id,
  title,
  sections: [
    {
      id: 'meta',
      title: 'SEO и настройки',
      fields: [
        { key: 'slug', label: 'URL (slug)', fallback: slug },
        { key: 'seo_title', label: 'SEO title', fallback: defaultTitle + ' — КриптоМетры' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: defaultSubtitle },
        { key: 'published', label: 'Статус публикации (published / draft)', fallback: 'draft' },
      ],
    },
    {
      id: 'hero',
      title: 'Обложка (Hero)',
      fields: [
        { key: 'chip', label: 'Метка над заголовком', fallback: 'КриптоМетры' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: defaultTitle },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: '' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: defaultSubtitle },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Узнать подробнее' },
        { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/system' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: '' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ],
    },
    {
      id: 'blocks',
      title: 'Текстовые блоки',
      fields: [
        { key: 'block_1_title', label: 'Блок #1 — заголовок', fallback: '' },
        { key: 'block_1_text', label: 'Блок #1 — текст', multiline: true, fallback: '' },
        { key: 'block_2_title', label: 'Блок #2 — заголовок', fallback: '' },
        { key: 'block_2_text', label: 'Блок #2 — текст', multiline: true, fallback: '' },
        { key: 'block_3_title', label: 'Блок #3 — заголовок', fallback: '' },
        { key: 'block_3_text', label: 'Блок #3 — текст', multiline: true, fallback: '' },
      ],
    },
    {
      id: 'cta',
      title: 'Финальный призыв (CTA)',
      fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Хочешь узнать больше?' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
        { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/mining-kvartiry' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'На главную' },
        { key: 'cta_secondary_url', label: 'Кнопка вторичная — ссылка', fallback: '/' },
      ],
    },
  ],
});

export const INFO_PAGES: ContentPage[] = [
  // ─── ЧТО ТАКОЕ КРИПТОМЕТРЫ ────────────────────────────────────────────────
  {
    id: 'about',
    title: 'Что такое КриптоМетры',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/about' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Что такое КриптоМетры — единица учёта вклада' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'КМ — внутренняя единица учёта вклада участника в развитие системы. Не криптовалюта, не ценная бумага.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Единица участия' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'КриптоМетр —' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'это вклад, не токен.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Внутренняя единица учёта вклада участника в развитие системы. КМ фиксирует участие — денежное или трудовое. Это не криптовалюта, не ценная бумага и не гарантированный инвестиционный инструмент.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Калькулятор КМ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'what',
        title: 'Что такое КМ',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Определение' },
          { key: 'title', label: 'Заголовок', fallback: 'Единица учёта вклада.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'КриптоМетр (КМ) — это внутренняя единица, которая фиксирует вклад участника в создание и развитие системы КриптоМетры. Вклад может быть денежным или трудовым. КМ отражает степень участия — и служит основанием для доступа к будущим возможностям системы.' },
        ],
      },
      {
        id: 'howget',
        title: 'Как получить КМ',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Способы получения' },
          { key: 'title', label: 'Заголовок', fallback: 'Деньгами или делом.' },
          { key: 'way_1_title', label: 'Способ #1', fallback: 'Денежный вклад' },
          { key: 'way_1_text', label: 'Способ #1 — описание', fallback: 'Прямое участие в фонде проекта конвертируется в КМ по расчётному курсу' },
          { key: 'way_2_title', label: 'Способ #2', fallback: 'Регистрация и анкета' },
          { key: 'way_2_text', label: 'Способ #2 — описание', fallback: 'Первичные действия участника при входе в систему' },
          { key: 'way_3_title', label: 'Способ #3', fallback: 'Запросы к ИИ' },
          { key: 'way_3_text', label: 'Способ #3 — описание', fallback: 'Каждый верифицированный запрос к ИИ АО КСИ создаёт единицу опыта и может быть основанием для КМ' },
          { key: 'way_4_title', label: 'Способ #4', fallback: 'Привлечение участников' },
          { key: 'way_4_text', label: 'Способ #4 — описание', fallback: 'Приглашение новых участников, рекламодателей, привлечение объектов' },
          { key: 'way_5_title', label: 'Способ #5', fallback: 'Репосты и медиа' },
          { key: 'way_5_text', label: 'Способ #5 — описание', fallback: 'Распространение материалов медиаплатформы' },
        ],
      },
      {
        id: 'disclaimer',
        title: 'Важный дисклеймер',
        fields: [
          { key: 'title', label: 'Заголовок', fallback: 'Что КМ — не является.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'КриптоМетр не является публичной криптовалютой, ценной бумагой или гарантированным инвестиционным инструментом. КМ не торгуется на биржах и не даёт права на получение дохода. Расчётная обеспеченность КМ может изменяться в зависимости от размера фонда и количества КМ в обращении. Участие в системе не является приобретением доли в недвижимости.' },
          { key: 'point_1', label: 'Пункт #1', fallback: 'Не криптовалюта' },
          { key: 'point_2', label: 'Пункт #2', fallback: 'Не ценная бумага' },
          { key: 'point_3', label: 'Пункт #3', fallback: 'Не гарантия доходности' },
          { key: 'point_4', label: 'Пункт #4', fallback: 'Не ДДУ и не доля в объекте' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Готов войти в систему?' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Фонд КриптоМетров' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/fond' },
        ],
      },
    ],
  },
  // ─── ИИ АО КСИ ────────────────────────────────────────────────────────────
  {
    id: 'ai-ksi',
    title: 'ИИ АО КСИ',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/ai-ksi' },
          { key: 'seo_title', label: 'SEO title', fallback: 'ИИ АО КСИ — интеллектуальный контур КриптоМетров' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Внутренний ИИ-контур проекта: как работает, с какими моделями, что накапливает.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'АО КСИ · Интеллектуальный контур' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'ИИ' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'АО КСИ' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Внутренний интеллектуальный контур проекта. Работает на внешних облачных моделях — GPT и других LLM. Каждый запрос пополняет базу знаний системы, а не обучает внешние модели.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Как работает запрос' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/how-ai' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Про АО КСИ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'what',
        title: 'Что такое ИИ АО КСИ',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Суть' },
          { key: 'title', label: 'Заголовок', fallback: 'Не чат-бот. Контур.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'ИИ АО КСИ — это не просто чат-бот для ответов на вопросы. Это интеллектуальный операционный контур: система классификации задач, маршрутизации запросов, накопления опыта и взаимодействия с операторами. Он встроен в рабочую инфраструктуру управляющей компании.' },
        ],
      },
      {
        id: 'models',
        title: 'Модели и инфраструктура',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Инфраструктура' },
          { key: 'title', label: 'Заголовок', fallback: 'Облако сегодня. Свои серверы — завтра.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'На первом этапе ИИ работает на внешних облачных LLM: GPT, Claude и других. В будущем возможен перенос на собственные серверы и локальные модели — без зависимости от внешних провайдеров.' },
          { key: 'card_1_title', label: 'Карточка #1 — заголовок', fallback: 'GPT и LLM' },
          { key: 'card_1_text', label: 'Карточка #1 — текст', fallback: 'Внешние облачные модели для обработки типовых запросов' },
          { key: 'card_2_title', label: 'Карточка #2 — заголовок', fallback: 'Операторы КСИ' },
          { key: 'card_2_text', label: 'Карточка #2 — текст', fallback: 'Люди, которые проверяют сложные запросы и обеспечивают качество' },
          { key: 'card_3_title', label: 'Карточка #3 — заголовок', fallback: 'База знаний' },
          { key: 'card_3_text', label: 'Карточка #3 — текст', fallback: 'Внутренний реестр опыта, сценарии обработки, накопленные данные' },
          { key: 'card_4_title', label: 'Карточка #4 — заголовок', fallback: 'Локальные модели' },
          { key: 'card_4_text', label: 'Карточка #4 — текст', fallback: 'Перспектива: собственные серверы и независимые модели' },
        ],
      },
      {
        id: 'knowledge',
        title: 'База знаний',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '03 · База знаний' },
          { key: 'title', label: 'Заголовок', fallback: 'Каждый запрос — вклад в систему.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Ни один запрос не уходит бесследно. Он не обучает внешнюю модель напрямую — но пополняет внутренний реестр опыта КСИ: сценарии обработки, теги, категории, результаты и основания для начисления КМ. Так система становится умнее с каждым участником.' },
        ],
      },
      {
        id: 'operators',
        title: 'Операторы',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '04 · Люди в контуре' },
          { key: 'title', label: 'Заголовок', fallback: 'ИИ работает не один.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'За ИИ стоят операторы АО КСИ — люди, которые проверяют результаты сложных запросов, управляют качеством ответов и вносят правки. Это гибридная система: ИИ берёт скорость и объём, операторы — точность и ответственность.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Хочешь отправить запрос к ИИ?' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Как это работает' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/how-ai' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'О компании АО КСИ' },
          { key: 'cta_secondary_url', label: 'Кнопка вторичная — ссылка', fallback: '/ao-ksi' },
        ],
      },
    ],
  },
  // ─── АО КСИ ───────────────────────────────────────────────────────────────
  {
    id: 'ao-ksi',
    title: 'АО КСИ — управляющая компания',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/ao-ksi' },
          { key: 'seo_title', label: 'SEO title', fallback: 'АО КСИ — управляющая компания КриптоМетров' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'АО КриптоСтройИнвест — разработчик и оператор интеллектуальной инфраструктуры проекта.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'Управляющая компания · КриптоМетры' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'АО' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'КриптоСтройИнвест' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Управляющая компания, разработчик и оператор интеллектуальной инфраструктуры проекта КриптоМетры. Центр ответственности и технологического развития.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'ИИ АО КСИ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/ai-ksi' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Правовая модель' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'mission',
        title: 'Миссия',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Миссия' },
          { key: 'title', label: 'Заголовок', fallback: 'Центр ответственности системы.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'АО КСИ — не просто юридическое лицо. Это операционный центр, который создаёт и обслуживает инфраструктуру: ИИ-контур, медиаплатформу, реестры, партнёрские направления и административный интерфейс. Кооператив объединяет участников — АО КСИ обеспечивает работу системы.' },
        ],
      },
      {
        id: 'functions',
        title: 'Функции',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Что делает АО КСИ' },
          { key: 'title', label: 'Заголовок', fallback: 'Создаёт. Обслуживает. Развивает.' },
          { key: 'fn_1_title', label: 'Функция #1', fallback: 'ИИ-контур' },
          { key: 'fn_1_text', label: 'Функция #1 — описание', fallback: 'Создание и поддержка интеллектуального контура: GPT-интеграции, операторский слой, база знаний' },
          { key: 'fn_2_title', label: 'Функция #2', fallback: 'Медиаплатформа' },
          { key: 'fn_2_text', label: 'Функция #2 — описание', fallback: 'Разработка и ведение собственной медиаплатформы: контент, обучение, сообщество' },
          { key: 'fn_3_title', label: 'Функция #3', fallback: 'Операционный контур' },
          { key: 'fn_3_text', label: 'Функция #3 — описание', fallback: 'Обработка запросов участников, управление реестрами и начислением КМ' },
          { key: 'fn_4_title', label: 'Функция #4', fallback: 'Партнёрства' },
          { key: 'fn_4_text', label: 'Функция #4 — описание', fallback: 'Аккредитация девелоперов, рекламные направления, LSS и внешние интеграции' },
          { key: 'fn_5_title', label: 'Функция #5', fallback: 'Административный контур' },
          { key: 'fn_5_text', label: 'Функция #5 — описание', fallback: 'Инструменты для операторов, аналитика, управление контентом' },
          { key: 'fn_6_title', label: 'Функция #6', fallback: 'Правовая модель' },
          { key: 'fn_6_text', label: 'Функция #6 — описание', fallback: 'Юридическая архитектура проекта, защита прав участников' },
        ],
      },
      {
        id: 'cooperative',
        title: 'КСИ и кооператив',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '03 · Разделение ролей' },
          { key: 'title', label: 'Заголовок', fallback: 'Кооператив объединяет. КСИ обеспечивает.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Кооператив — это участники, их права и коллективное решение. АО КСИ — это технологический и операционный партнёр, который создаёт инфраструктуру, по которой участники движутся к своему жилью.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Хочешь стать частью системы?' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'ИИ АО КСИ' },
          { key: 'cta_secondary_url', label: 'Кнопка вторичная — ссылка', fallback: '/ai-ksi' },
        ],
      },
    ],
  },
  // ─── ФОНД КРИПТОМЕТРОВ ────────────────────────────────────────────────────
  {
    id: 'fond',
    title: 'Фонд КриптоМетров',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/fond' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Фонд КриптоМетров — денежная база проекта' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Как пополняется фонд, расчётная обеспеченность КМ и связь с медиаплатформой.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Финансовая основа' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Фонд' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'КриптоМетров.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Денежная база проекта. 50% рекламных доходов медиаплатформы направляется в фонд. Расчётная обеспеченность КМ зависит от размера фонда и количества КМ в обращении.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Калькулятор КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/calculator' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Что такое КМ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'structure',
        title: 'Откуда берётся фонд',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Источники' },
          { key: 'title', label: 'Заголовок', fallback: 'Деньги системы — деньги участников.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Фонд КриптоМетров формируется из нескольких источников. Ключевой — рекламные доходы медиаплатформы: до 50% от них может направляться в фонд. Дополнительно фонд пополняется взносами участников и партнёрскими поступлениями.' },
          { key: 'src_1_title', label: 'Источник #1', fallback: 'Рекламные доходы' },
          { key: 'src_1_text', label: 'Источник #1 — описание', fallback: 'До 50% доходов медиаплатформы направляется в фонд' },
          { key: 'src_2_title', label: 'Источник #2', fallback: 'Взносы участников' },
          { key: 'src_2_text', label: 'Источник #2 — описание', fallback: 'Денежные вклады при вступлении и активном участии' },
          { key: 'src_3_title', label: 'Источник #3', fallback: 'Партнёрские поступления' },
          { key: 'src_3_text', label: 'Источник #3 — описание', fallback: 'Комиссии от аккредитованных девелоперов и рекламодателей' },
        ],
      },
      {
        id: 'coverage',
        title: 'Расчётная обеспеченность',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Формула' },
          { key: 'title', label: 'Заголовок', fallback: 'Фонд ÷ КМ в обращении.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Расчётная обеспеченность одного КМ рассчитывается как: размер фонда / количество КМ в обращении. Это ориентировочная величина. Она может расти при пополнении фонда и снижаться при выпуске новых КМ. Расчётная обеспеченность не является обещанием доходности или гарантией выкупа.' },
          { key: 'disclaimer', label: 'Дисклеймер под формулой', fallback: 'Расчётная обеспеченность — ориентировочный показатель. Не является гарантией доходности, обещанием выкупа или инвестиционным предложением.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Рассчитай свою позицию.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Калькулятор КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/calculator' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Получить КМ' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/mining-kvartiry' },
        ],
      },
    ],
  },
  // ─── КАЛЬКУЛЯТОР КМ ───────────────────────────────────────────────────────
  {
    id: 'calculator',
    title: 'Калькулятор КМ',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/calculator' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Калькулятор КМ — сколько КриптоМетров ты получишь' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Рассчитай количество КМ за денежный вклад и действия в системе.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Калькулятор' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Калькулятор' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'КМ.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Рассчитай, сколько КриптоМетров ты получишь за денежный вклад и действия в системе. Расчёт ориентировочный и не является гарантией доходности.' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'rates',
        title: 'Ставки начисления',
        fields: [
          { key: 'money_rate', label: 'КМ за 1000 руб. вклада', fallback: '1' },
          { key: 'action_register', label: 'КМ за регистрацию', fallback: '0.5' },
          { key: 'action_anketa', label: 'КМ за анкету квартиры', fallback: '1' },
          { key: 'action_ai', label: 'КМ за запрос к ИИ', fallback: '0.2' },
          { key: 'action_repost', label: 'КМ за репост', fallback: '0.1' },
          { key: 'action_invite', label: 'КМ за приглашение участника', fallback: '2' },
          { key: 'action_object', label: 'КМ за передачу объекта', fallback: '5' },
          { key: 'action_buyer', label: 'КМ за привлечение покупателя', fallback: '10' },
          { key: 'action_advertiser', label: 'КМ за привлечение рекламодателя', fallback: '15' },
          { key: 'fund_scenario_1', label: 'Сценарий #1 — размер фонда (руб.)', fallback: '1000000' },
          { key: 'fund_scenario_2', label: 'Сценарий #2 — размер фонда (руб.)', fallback: '10000000' },
          { key: 'fund_scenario_3', label: 'Сценарий #3 — размер фонда (руб.)', fallback: '100000000' },
          { key: 'disclaimer', label: 'Дисклеймер', fallback: 'Расчёт ориентировочный. Не является обещанием доходности, гарантией выкупа или инвестиционным предложением. Ставки могут изменяться.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Начни накапливать КМ прямо сейчас.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Про фонд' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/fond' },
        ],
      },
    ],
  },
  // ─── МЕДИАПЛАТФОРМА ───────────────────────────────────────────────────────
  {
    id: 'media',
    title: 'Медиаплатформа',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/media' },
        { key: 'seo_title', label: 'SEO title', fallback: 'Медиаплатформа КриптоМетров — публичная среда обучения ИИ' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Новости, кейсы, объекты, аналитика — на входе. Подкасты, видео, обзоры — на выходе.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Медиа' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Медиа' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'платформа.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Публичная среда обучения ИИ АО КСИ. Реальные новости, кейсы и объекты — на входе. Подкасты, видео, аналитика и медиасериалы — на выходе.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'КриптоЭфир' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/cryptoair' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Для рекламодателей' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'flow', title: 'Схема работы', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Как работает медиаплатформа' },
        { key: 'title', label: 'Заголовок', fallback: 'Вход — данные. Выход — контент.' },
        { key: 'in_1', label: 'На входе #1', fallback: 'Новости рынка' },
        { key: 'in_2', label: 'На входе #2', fallback: 'Кейсы и объекты' },
        { key: 'in_3', label: 'На входе #3', fallback: 'Запросы участников' },
        { key: 'in_4', label: 'На входе #4', fallback: 'Комментарии и события' },
        { key: 'out_1', label: 'На выходе #1', fallback: 'Подкасты' },
        { key: 'out_2', label: 'На выходе #2', fallback: 'Видео' },
        { key: 'out_3', label: 'На выходе #3', fallback: 'Аналитика' },
        { key: 'out_4', label: 'На выходе #4', fallback: 'Медиасериалы' },
      ]},
      { id: 'fund', title: 'Связь с фондом', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Медиа и фонд' },
        { key: 'title', label: 'Заголовок', fallback: 'Реклама питает фонд.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'До 50% рекламных доходов медиаплатформы направляется в Фонд КриптоМетров. Чем больше аудитория и рекламодателей — тем крепче финансовая база системы и выше расчётная обеспеченность КМ.' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Хочешь участвовать в медиа?' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'КриптоЭфир' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/cryptoair' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Стать рекламодателем' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/for-advertisers' },
      ]},
    ],
  },
  // ─── КАК РАБОТАЕТ ЗАПРОС К ИИ ─────────────────────────────────────────────
  {
    id: 'how-ai',
    title: 'Как работает запрос к ИИ',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/how-ai' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Как работает запрос к ИИ АО КСИ' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Путь запроса: от участника через классификатор к GPT или оператору — и обратно с единицей опыта.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'ИИ АО КСИ · Схема работы' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Путь запроса' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'к результату.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'От участника до ответа — через классификатор, GPT, операторов и реестр опыта. Каждый запрос что-то создаёт.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Про ИИ АО КСИ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/ai-ksi' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Реестр опыта' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'steps',
        title: 'Шаги маршрута',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Маршрут запроса · 9 шагов' },
          { key: 'title', label: 'Заголовок', fallback: 'Каждый запрос проходит свой путь.' },
          { key: 'step_1', label: 'Шаг 1', fallback: 'Участник отправляет запрос' },
          { key: 'step_1_desc', label: 'Шаг 1 — описание', fallback: 'Через интерфейс системы — текстом, формой или голосом' },
          { key: 'step_2', label: 'Шаг 2', fallback: 'Классификатор анализирует задачу' },
          { key: 'step_2_desc', label: 'Шаг 2 — описание', fallback: 'Внутренний ИИ-контур определяет тип, сложность и маршрут' },
          { key: 'step_3', label: 'Шаг 3', fallback: 'Простой запрос → GPT' },
          { key: 'step_3_desc', label: 'Шаг 3 — описание', fallback: 'Типовые задачи обрабатываются автоматически облачной моделью' },
          { key: 'step_4', label: 'Шаг 4', fallback: 'Сложный запрос → Оператор' },
          { key: 'step_4_desc', label: 'Шаг 4 — описание', fallback: 'Нестандартные задачи передаются оператору АО КСИ' },
          { key: 'step_5', label: 'Шаг 5', fallback: 'Подключение дополнительных моделей' },
          { key: 'step_5_desc', label: 'Шаг 5 — описание', fallback: 'При необходимости задействуются специализированные модели и советники' },
          { key: 'step_6', label: 'Шаг 6', fallback: 'Оператор проверяет результат' },
          { key: 'step_6_desc', label: 'Шаг 6 — описание', fallback: 'Человек верифицирует качество и точность ответа' },
          { key: 'step_7', label: 'Шаг 7', fallback: 'Ответ возвращается участнику' },
          { key: 'step_7_desc', label: 'Шаг 7 — описание', fallback: 'Финальный результат доставляется в удобном формате' },
          { key: 'step_8', label: 'Шаг 8', fallback: 'Создаётся единица опыта' },
          { key: 'step_8_desc', label: 'Шаг 8 — описание', fallback: 'Запрос, результат, оператор, модель и теги фиксируются в Реестре опыта' },
          { key: 'step_9', label: 'Шаг 9', fallback: 'Начисляются КМ' },
          { key: 'step_9_desc', label: 'Шаг 9 — описание', fallback: 'При наличии основания участнику начисляются КриптоМетры' },
        ],
      },
      {
        id: 'result',
        title: 'Что остаётся',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Итог' },
          { key: 'title', label: 'Заголовок', fallback: 'Запрос не исчезает.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Каждый завершённый запрос оставляет след в системе. Единица опыта — это не просто лог. Это строительный материал для будущего: она пополняет базу знаний, влияет на качество следующих ответов и служит основанием для начисления КМ.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Хочешь отправить свой первый запрос?' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Реестр опыта' },
          { key: 'cta_secondary_url', label: 'Кнопка вторичная — ссылка', fallback: '/registry-exp' },
        ],
      },
    ],
  },
  // ─── РЕЕСТР ОПЫТА ─────────────────────────────────────────────────────────
  {
    id: 'registry-exp',
    title: 'Реестр опыта',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/registry-exp' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Реестр опыта — КриптоМетры' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Каждый подтверждённый результат становится единицей опыта и фиксируется в реестре.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Реестр опыта' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Реестр' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'опыта.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Каждый подтверждённый результат — это единица опыта. Она фиксирует запрос, участника, оператора, модель и дату. И может служить основанием для начисления КМ.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Как работает ИИ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/how-ai' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Реестр КМ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'unit',
        title: 'Что такое единица опыта',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Единица опыта' },
          { key: 'title', label: 'Заголовок', fallback: 'Результат, который остаётся.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Единица опыта — это структурированная запись о завершённом взаимодействии. Она создаётся каждый раз, когда запрос прошёл через контур ИИ АО КСИ и был верифицирован оператором.' },
          { key: 'field_1', label: 'Поле #1', fallback: 'Запрос' },
          { key: 'field_1_desc', label: 'Поле #1 — описание', fallback: 'Исходный запрос участника' },
          { key: 'field_2', label: 'Поле #2', fallback: 'Результат' },
          { key: 'field_2_desc', label: 'Поле #2 — описание', fallback: 'Финальный ответ или решение' },
          { key: 'field_3', label: 'Поле #3', fallback: 'Участник' },
          { key: 'field_3_desc', label: 'Поле #3 — описание', fallback: 'ID или псевдоним автора запроса' },
          { key: 'field_4', label: 'Поле #4', fallback: 'Оператор' },
          { key: 'field_4_desc', label: 'Поле #4 — описание', fallback: 'Оператор АО КСИ, верифицировавший результат' },
          { key: 'field_5', label: 'Поле #5', fallback: 'Модель' },
          { key: 'field_5_desc', label: 'Поле #5 — описание', fallback: 'ИИ-модель, обработавшая запрос' },
          { key: 'field_6', label: 'Поле #6', fallback: 'Дата' },
          { key: 'field_6_desc', label: 'Поле #6 — описание', fallback: 'Временная метка верификации' },
          { key: 'field_7', label: 'Поле #7', fallback: 'Теги' },
          { key: 'field_7_desc', label: 'Поле #7 — описание', fallback: 'Категория и тематика запроса' },
          { key: 'field_8', label: 'Поле #8', fallback: 'Качество' },
          { key: 'field_8_desc', label: 'Поле #8 — описание', fallback: 'Оценка результата от 1 до 5' },
          { key: 'field_9', label: 'Поле #9', fallback: 'Основание для КМ' },
          { key: 'field_9_desc', label: 'Поле #9 — описание', fallback: 'Есть ли основание для начисления КриптоМетров' },
        ],
      },
      {
        id: 'future',
        title: 'Будущее реестра',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Перспектива' },
          { key: 'title', label: 'Заголовок', fallback: 'Сейчас внутри. Потом — в цепи.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'На первом этапе реестр — внутренний. Все записи хранятся в защищённой базе КСИ. В перспективе возможна hash-фиксация каждой единицы опыта и добавление блокчейн-слоя: это сделает реестр публично верифицируемым и неизменяемым.' },
          { key: 'stage_1_title', label: 'Этап #1', fallback: 'Внутренний реестр' },
          { key: 'stage_1_text', label: 'Этап #1 — описание', fallback: 'Защищённая база данных КСИ с полным контролем качества' },
          { key: 'stage_2_title', label: 'Этап #2', fallback: 'Hash-фиксация' },
          { key: 'stage_2_text', label: 'Этап #2 — описание', fallback: 'Каждая единица опыта получает уникальный хэш — цифровой отпечаток' },
          { key: 'stage_3_title', label: 'Этап #3', fallback: 'Блокчейн-слой' },
          { key: 'stage_3_text', label: 'Этап #3 — описание', fallback: 'Публичная верификация и неизменяемость через распределённый реестр' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Начни создавать свои единицы опыта.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Кнопка — ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Как работает ИИ' },
          { key: 'cta_secondary_url', label: 'Кнопка вторичная — ссылка', fallback: '/how-ai' },
        ],
      },
    ],
  },
  // ─── РЕЕСТР КРИПТОМЕТРОВ ──────────────────────────────────────────────────
  {
    id: 'registry-km',
    title: 'Реестр КриптоМетров',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/registry-km' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Реестр КриптоМетров — история начислений и основания' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Публичная история начислений, списаний, оснований и связь КМ с единицами опыта.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Реестр' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Реестр' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'КриптоМетров.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'История начислений, списаний и блокировок КМ. Каждая запись связана с единицей опыта. В перспективе — hash-фиксация и блокчейн-слой.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Реестр опыта' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/registry-exp' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Что такое КМ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'operations',
        title: 'Типы операций',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Типы записей' },
          { key: 'title', label: 'Заголовок', fallback: 'Каждое движение фиксируется.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Реестр КМ хранит полную историю всех операций с единицами. Начисление, списание, блокировка — каждая запись содержит основание, участника, дату и ссылку на единицу опыта.' },
          { key: 'op_1', label: 'Операция #1', fallback: 'Начисление' },
          { key: 'op_1_desc', label: 'Операция #1 — описание', fallback: 'КМ начисляются за верифицированные действия участника' },
          { key: 'op_2', label: 'Операция #2', fallback: 'Списание' },
          { key: 'op_2_desc', label: 'Операция #2 — описание', fallback: 'КМ могут списываться при использовании в программах системы' },
          { key: 'op_3', label: 'Операция #3', fallback: 'Блокировка' },
          { key: 'op_3_desc', label: 'Операция #3 — описание', fallback: 'Временная блокировка КМ при участии в целевых программах' },
          { key: 'op_4', label: 'Операция #4', fallback: 'Основание' },
          { key: 'op_4_desc', label: 'Операция #4 — описание', fallback: 'Каждая операция привязана к конкретному основанию и единице опыта' },
        ],
      },
      {
        id: 'link_exp',
        title: 'Связь с реестром опыта',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Связь с опытом' },
          { key: 'title', label: 'Заголовок', fallback: 'КМ — следствие опыта.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Каждое начисление КМ напрямую связано с единицей опыта в Реестре опыта. Нельзя получить КМ без верифицированного результата. Эта связь обеспечивает прозрачность и обоснованность каждого начисления.' },
        ],
      },
      {
        id: 'future',
        title: 'Будущее реестра',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '03 · Перспектива' },
          { key: 'title', label: 'Заголовок', fallback: 'Сейчас централизованно. Потом — в цепи.' },
          { key: 'stage_1_title', label: 'Этап #1', fallback: 'Централизованный реестр' },
          { key: 'stage_1_text', label: 'Этап #1 — описание', fallback: 'База данных КСИ с полным аудитом и контролем' },
          { key: 'stage_2_title', label: 'Этап #2', fallback: 'Hash-фиксация' },
          { key: 'stage_2_text', label: 'Этап #2 — описание', fallback: 'Каждая запись получает уникальный цифровой отпечаток' },
          { key: 'stage_3_title', label: 'Этап #3', fallback: 'Блокчейн-слой' },
          { key: 'stage_3_text', label: 'Этап #3 — описание', fallback: 'Публичная верификация и неизменяемость через распределённый реестр' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Начни формировать свою историю КМ.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Реестр опыта' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/registry-exp' },
        ],
      },
    ],
  },
  // ─── КООПЕРАТИВНАЯ МОДЕЛЬ ─────────────────────────────────────────────────
  {
    id: 'cooperative',
    title: 'Кооперативная модель',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/cooperative' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Кооперативная модель КриптоМетров' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Кооператив — юридическая форма объединения участников. Не ДДУ, не продажа квартиры.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Правовая форма' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Кооперативная' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'модель.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Кооператив — юридическая форма объединения участников. Участие не является договором долевого участия, покупкой квартиры или гарантией получения объекта недвижимости.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Правовая модель' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/legal' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'АО КСИ' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'what',
        title: 'Что такое кооператив',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Определение' },
          { key: 'title', label: 'Заголовок', fallback: 'Объединение. Не продажа.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Кооператив — это юридическая форма добровольного объединения участников для достижения общей цели. В контексте КриптоМетров — это структура, которая позволяет участникам действовать совместно: формировать фонд, заказывать девелопмент, контролировать процессы. Участие в кооперативе не равно покупке квартиры.' },
          { key: 'not_1', label: 'Чем НЕ является #1', fallback: 'Не ДДУ (договор долевого участия)' },
          { key: 'not_2', label: 'Чем НЕ является #2', fallback: 'Не покупка квартиры' },
          { key: 'not_3', label: 'Чем НЕ является #3', fallback: 'Не гарантия получения объекта' },
          { key: 'not_4', label: 'Чем НЕ является #4', fallback: 'Не инвестиционный продукт' },
        ],
      },
      {
        id: 'roles',
        title: 'Роли в модели',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Кооператив и КСИ' },
          { key: 'title', label: 'Заголовок', fallback: 'Разные роли. Единая система.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Кооператив объединяет участников и является носителем их коллективных прав. АО КСИ создаёт и обслуживает инфраструктуру: ИИ, медиаплатформу, операционный контур. Кооператив — это люди. КСИ — это инструмент.' },
        ],
      },
      {
        id: 'future',
        title: 'Целевые программы',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '03 · Перспектива' },
          { key: 'title', label: 'Заголовок', fallback: 'В будущем — целевые программы.' },
          { key: 'text', label: 'Текст', multiline: true, fallback: 'Кооператив может в будущем запускать отдельные целевые программы, связанные с недвижимостью. Каждая такая программа будет иметь собственные условия, правила участия и юридическое оформление. Участие в текущей системе КриптоМетров не даёт автоматического права на участие в будущих программах.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Стань частью кооператива.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Правовая модель' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/legal' },
        ],
      },
    ],
  },
  // ─── ДОРОЖНАЯ КАРТА ───────────────────────────────────────────────────────
  {
    id: 'roadmap',
    title: 'Дорожная карта',
    sections: [
      {
        id: 'meta',
        title: 'SEO и настройки',
        fields: [
          { key: 'slug', label: 'URL (slug)', fallback: '/roadmap' },
          { key: 'seo_title', label: 'SEO title', fallback: 'Дорожная карта КриптоМетров' },
          { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Этапы развития проекта: от сайта до блокчейн-реестра и первых целевых программ.' },
          { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
        ],
      },
      {
        id: 'hero',
        title: 'Обложка',
        fields: [
          { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Этапы развития' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Дорожная' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'карта.' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'От сайта и первых участников — до блокчейн-реестра и целевых программ с недвижимостью. Каждый этап строится на предыдущем.' },
          { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
        ],
      },
      {
        id: 'stages',
        title: 'Этапы',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: '12 этапов · От запуска до первых программ' },
          { key: 'title', label: 'Заголовок', fallback: 'Строим последовательно.' },
          { key: 'stage_1_title', label: 'Этап 1', fallback: 'Сайт' },
          { key: 'stage_1_desc', label: 'Этап 1 — описание', fallback: 'Публичный сайт, главная страница, описание системы' },
          { key: 'stage_1_status', label: 'Этап 1 — статус', fallback: 'done' },
          { key: 'stage_2_title', label: 'Этап 2', fallback: 'Медиа-разделы' },
          { key: 'stage_2_desc', label: 'Этап 2 — описание', fallback: 'Страницы системы, архитектура разделов, хаб навигации' },
          { key: 'stage_2_status', label: 'Этап 2 — статус', fallback: 'done' },
          { key: 'stage_3_title', label: 'Этап 3', fallback: 'Регистрация участников' },
          { key: 'stage_3_desc', label: 'Этап 3 — описание', fallback: 'Форма входа, личные кабинеты, профили участников' },
          { key: 'stage_3_status', label: 'Этап 3 — статус', fallback: 'done' },
          { key: 'stage_4_title', label: 'Этап 4', fallback: 'Личный кабинет' },
          { key: 'stage_4_desc', label: 'Этап 4 — описание', fallback: 'Баланс КМ, история, уровни участника' },
          { key: 'stage_4_status', label: 'Этап 4 — статус', fallback: 'done' },
          { key: 'stage_5_title', label: 'Этап 5', fallback: 'Реестр КМ' },
          { key: 'stage_5_desc', label: 'Этап 5 — описание', fallback: 'Публичная история начислений и оснований' },
          { key: 'stage_5_status', label: 'Этап 5 — статус', fallback: 'active' },
          { key: 'stage_6_title', label: 'Этап 6', fallback: 'Калькулятор КМ' },
          { key: 'stage_6_desc', label: 'Этап 6 — описание', fallback: 'Интерактивный расчёт КМ и сценарной обеспеченности' },
          { key: 'stage_6_status', label: 'Этап 6 — статус', fallback: 'active' },
          { key: 'stage_7_title', label: 'Этап 7', fallback: 'ИИ-запросы' },
          { key: 'stage_7_desc', label: 'Этап 7 — описание', fallback: 'Интерфейс для отправки запросов к ИИ АО КСИ' },
          { key: 'stage_7_status', label: 'Этап 7 — статус', fallback: 'active' },
          { key: 'stage_8_title', label: 'Этап 8', fallback: 'Медиаплатформа' },
          { key: 'stage_8_desc', label: 'Этап 8 — описание', fallback: 'Полноценная медиаплатформа: контент, обучение, сообщество' },
          { key: 'stage_8_status', label: 'Этап 8 — статус', fallback: 'planned' },
          { key: 'stage_9_title', label: 'Этап 9', fallback: 'Фонд' },
          { key: 'stage_9_desc', label: 'Этап 9 — описание', fallback: 'Запуск механизма пополнения фонда и расчёта обеспеченности' },
          { key: 'stage_9_status', label: 'Этап 9 — статус', fallback: 'planned' },
          { key: 'stage_10_title', label: 'Этап 10', fallback: 'Кооперативная структура' },
          { key: 'stage_10_desc', label: 'Этап 10 — описание', fallback: 'Юридическое оформление кооператива и прав участников' },
          { key: 'stage_10_status', label: 'Этап 10 — статус', fallback: 'planned' },
          { key: 'stage_11_title', label: 'Этап 11', fallback: 'Блокчейн-реестр' },
          { key: 'stage_11_desc', label: 'Этап 11 — описание', fallback: 'Hash-фиксация и публичная верификация реестра КМ и опыта' },
          { key: 'stage_11_status', label: 'Этап 11 — статус', fallback: 'planned' },
          { key: 'stage_12_title', label: 'Этап 12', fallback: 'Целевые программы' },
          { key: 'stage_12_desc', label: 'Этап 12 — описание', fallback: 'Первые целевые программы кооператива, связанные с недвижимостью' },
          { key: 'stage_12_status', label: 'Этап 12 — статус', fallback: 'planned' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title', label: 'Заголовок CTA', fallback: 'Войди в систему на раннем этапе.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Кооперативная модель' },
          { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/cooperative' },
        ],
      },
    ],
  },
  // ─── КРИПТОЭФИР ───────────────────────────────────────────────────────────
  {
    id: 'cryptoair',
    title: 'КриптоЭфир',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/cryptoair' },
        { key: 'seo_title', label: 'SEO title', fallback: 'КриптоЭфир — ИИ-радио о недвижимости и девелопменте' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Ежедневные обзоры, дайджесты, подкасты и аудиоразборы о рынке недвижимости от ИИ АО КСИ.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · ИИ-радио' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Крипто' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'Эфир.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'ИИ-радио о недвижимости, девелопменте, земле, технологиях и кооперативной экономике. Каждый выпуск — блок публичного обучения системы.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Медиаплатформа' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/media' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Про ИИ АО КСИ' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'formats', title: 'Форматы', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Форматы выпусков' },
        { key: 'title', label: 'Заголовок', fallback: 'Разные форматы. Один смысл.' },
        { key: 'fmt_1_title', label: 'Формат #1', fallback: 'Ежедневные обзоры' },
        { key: 'fmt_1_desc', label: 'Формат #1 — описание', fallback: 'Краткий дайджест рынка недвижимости за сутки' },
        { key: 'fmt_2_title', label: 'Формат #2', fallback: 'Дайджесты Telegram' },
        { key: 'fmt_2_desc', label: 'Формат #2 — описание', fallback: 'Агрегация и анализ публикаций из профильных каналов' },
        { key: 'fmt_3_title', label: 'Формат #3', fallback: 'Подкасты' },
        { key: 'fmt_3_desc', label: 'Формат #3 — описание', fallback: 'Длинные разборы тем: земля, девелопмент, кооперация' },
        { key: 'fmt_4_title', label: 'Формат #4', fallback: 'Аудиоразборы' },
        { key: 'fmt_4_desc', label: 'Формат #4 — описание', fallback: 'ИИ-комментарий к кейсу, объекту или событию' },
        { key: 'fmt_5_title', label: 'Формат #5', fallback: 'Видео с абстрактным фоном' },
        { key: 'fmt_5_desc', label: 'Формат #5 — описание', fallback: 'Видеовыпуски с нейрофоном и голосом ИИ-ведущего' },
      ]},
      { id: 'episodes', title: 'Управление выпусками', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Выпуски' },
        { key: 'title', label: 'Заголовок', fallback: 'Последние выпуски.' },
        { key: 'ep_1_title', label: 'Выпуск #1 — название', fallback: '' },
        { key: 'ep_1_desc', label: 'Выпуск #1 — описание', multiline: true, fallback: '' },
        { key: 'ep_1_url', label: 'Выпуск #1 — ссылка/аудио', fallback: '' },
        { key: 'ep_1_cover', label: 'Выпуск #1 — обложка', type: 'image', fallback: '' },
        { key: 'ep_1_date', label: 'Выпуск #1 — дата', fallback: '' },
        { key: 'ep_1_tags', label: 'Выпуск #1 — теги', fallback: '' },
        { key: 'ep_1_status', label: 'Выпуск #1 — статус (published/draft)', fallback: 'draft' },
        { key: 'ep_2_title', label: 'Выпуск #2 — название', fallback: '' },
        { key: 'ep_2_desc', label: 'Выпуск #2 — описание', multiline: true, fallback: '' },
        { key: 'ep_2_url', label: 'Выпуск #2 — ссылка/аудио', fallback: '' },
        { key: 'ep_2_cover', label: 'Выпуск #2 — обложка', type: 'image', fallback: '' },
        { key: 'ep_2_date', label: 'Выпуск #2 — дата', fallback: '' },
        { key: 'ep_2_tags', label: 'Выпуск #2 — теги', fallback: '' },
        { key: 'ep_2_status', label: 'Выпуск #2 — статус (published/draft)', fallback: 'draft' },
        { key: 'ep_3_title', label: 'Выпуск #3 — название', fallback: '' },
        { key: 'ep_3_desc', label: 'Выпуск #3 — описание', multiline: true, fallback: '' },
        { key: 'ep_3_url', label: 'Выпуск #3 — ссылка/аудио', fallback: '' },
        { key: 'ep_3_cover', label: 'Выпуск #3 — обложка', type: 'image', fallback: '' },
        { key: 'ep_3_date', label: 'Выпуск #3 — дата', fallback: '' },
        { key: 'ep_3_tags', label: 'Выпуск #3 — теги', fallback: '' },
        { key: 'ep_3_status', label: 'Выпуск #3 — статус (published/draft)', fallback: 'draft' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Стань частью медиаэкосистемы.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Медиаплатформа' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/media' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Для рекламодателей' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/for-advertisers' },
      ]},
    ],
  },
  // ─── ДЛЯ УЧАСТНИКОВ ───────────────────────────────────────────────────────
  {
    id: 'for-members',
    title: 'Для участников',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/for-members' },
        { key: 'seo_title', label: 'SEO title', fallback: 'Для участников КриптоМетров — майни чем владеешь' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Покупатель, риелтор, брокер, девелопер, землевладелец — у каждого свой способ майнить КМ.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Участие' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Майни тем,' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'что у тебя есть.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Каждый участник вносит вклад тем, что у него есть. Деньги, объекты, экспертиза, внимание — всё это работает в системе КриптоМетров.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Калькулятор КМ' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'roles', title: 'Роли участников', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Кто ты в системе' },
        { key: 'title', label: 'Заголовок', fallback: 'Каждая роль — свой вклад.' },
        { key: 'role_1_title', label: 'Роль #1', fallback: 'Покупатель' },
        { key: 'role_1_desc', label: 'Роль #1 — как майнит', fallback: 'Анкеты квартир, запросы к ИИ, обратная связь по объектам' },
        { key: 'role_2_title', label: 'Роль #2', fallback: 'Риелтор' },
        { key: 'role_2_desc', label: 'Роль #2 — как майнит', fallback: 'Объекты, покупатели, сделки, рыночная аналитика' },
        { key: 'role_3_title', label: 'Роль #3', fallback: 'Брокер' },
        { key: 'role_3_desc', label: 'Роль #3 — как майнит', fallback: 'Сделки, контакты, финансовая экспертиза' },
        { key: 'role_4_title', label: 'Роль #4', fallback: 'Девелопер' },
        { key: 'role_4_desc', label: 'Роль #4 — как майнит', fallback: 'Кейсы, опыт строительства, экспертиза по объектам' },
        { key: 'role_5_title', label: 'Роль #5', fallback: 'Землевладелец' },
        { key: 'role_5_desc', label: 'Роль #5 — как майнит', fallback: 'Передача участков, земельные активы для системы' },
        { key: 'role_6_title', label: 'Роль #6', fallback: 'Рекламодатель' },
        { key: 'role_6_desc', label: 'Роль #6 — как майнит', fallback: 'Поддержка медиаплатформы, спонсорство выпусков' },
        { key: 'role_7_title', label: 'Роль #7', fallback: 'Эксперт' },
        { key: 'role_7_desc', label: 'Роль #7 — как майнит', fallback: 'Знания, консультации, запросы к ИИ, обучение системы' },
        { key: 'role_8_title', label: 'Роль #8', fallback: 'Зритель' },
        { key: 'role_8_desc', label: 'Роль #8 — как майнит', fallback: 'Внимание, репосты, комментарии, реакции на контент' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Начни майнить прямо сейчас.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Что такое КМ' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/about' },
      ]},
    ],
  },
  // ─── ДЛЯ РЕКЛАМОДАТЕЛЕЙ ───────────────────────────────────────────────────
  {
    id: 'for-advertisers',
    title: 'Для рекламодателей',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/for-advertisers' },
        { key: 'seo_title', label: 'SEO title', fallback: 'Для рекламодателей — КриптоМетры Медиа' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Форматы рекламы, спонсорство и спецпроекты в медиаплатформе КриптоМетров.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры Медиа · Партнёрства' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Для' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'рекламодателей.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Рекламодатель участвует в создании медийной инфраструктуры рынка недвижимости. Часть рекламного дохода направляется в Фонд КриптоМетров.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Стать рекламодателем' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/for-advertisers' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Медиаплатформа' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'formats', title: 'Форматы рекламы', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Форматы' },
        { key: 'title', label: 'Заголовок', fallback: 'Шесть форматов участия.' },
        { key: 'fmt_1_title', label: 'Формат #1', fallback: 'Спонсорство выпуска' },
        { key: 'fmt_1_desc', label: 'Формат #1 — описание', fallback: 'Бренд как партнёр конкретного выпуска КриптоЭфира или медиаплатформы' },
        { key: 'fmt_2_title', label: 'Формат #2', fallback: 'Интеграция' },
        { key: 'fmt_2_desc', label: 'Формат #2 — описание', fallback: 'Органичное упоминание или демонстрация продукта в контексте контента' },
        { key: 'fmt_3_title', label: 'Формат #3', fallback: 'Обзор' },
        { key: 'fmt_3_desc', label: 'Формат #3 — описание', fallback: 'Развёрнутый разбор объекта, продукта или проекта от ИИ АО КСИ' },
        { key: 'fmt_4_title', label: 'Формат #4', fallback: 'Спецпроект' },
        { key: 'fmt_4_desc', label: 'Формат #4 — описание', fallback: 'Серия выпусков или мини-сериал по теме рекламодателя' },
        { key: 'fmt_5_title', label: 'Формат #5', fallback: 'ИИ-паспорт' },
        { key: 'fmt_5_desc', label: 'Формат #5 — описание', fallback: 'Структурированное ИИ-описание объекта или компании для базы знаний' },
        { key: 'fmt_6_title', label: 'Формат #6', fallback: 'Подкаст-партнёрство' },
        { key: 'fmt_6_desc', label: 'Формат #6 — описание', fallback: 'Совместный подкаст с экспертом рекламодателя и ИИ-ведущим' },
      ]},
      { id: 'why', title: 'Зачем это рекламодателю', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Ценность' },
        { key: 'title', label: 'Заголовок', fallback: 'Не просто реклама. Инфраструктура.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'Рекламодатель в КриптоМетрах — это не просто покупатель показов. Это участник строительства медийной инфраструктуры рынка недвижимости. Контент живёт долго, попадает в базу знаний ИИ и работает на аудиторию профессионалов рынка.' },
        { key: 'point_1', label: 'Аргумент #1', fallback: 'Аудитория профессионалов рынка недвижимости' },
        { key: 'point_2', label: 'Аргумент #2', fallback: 'Контент попадает в базу знаний ИИ АО КСИ' },
        { key: 'point_3', label: 'Аргумент #3', fallback: 'Часть дохода пополняет Фонд КриптоМетров' },
        { key: 'point_4', label: 'Аргумент #4', fallback: 'Долгосрочное присутствие в медиаэкосистеме' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Стань частью медийной инфраструктуры рынка.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Написать нам' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/faq' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Медиаплатформа' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/media' },
      ]},
    ],
  },
  // ─── LSS ──────────────────────────────────────────────────────────────────
  {
    id: 'lss',
    title: 'LSS — Служба земельного поиска',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/lss' },
        { key: 'seo_title', label: 'SEO title', fallback: 'LSS — Служба земельного поиска КриптоМетров' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'ИИ-поддержанный поиск земельных возможностей: участки, локации, собственники, потенциал.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Land Search Service' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Служба' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'земельного поиска.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'ИИ-поддержанный поиск земельных возможностей. Скрытые площадки, потенциальные участки, анализ локаций и собственников — всё через интеллектуальный контур КСИ.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Передать участок' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Задать вопрос ИИ' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'what', title: 'Что такое LSS', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Суть' },
        { key: 'title', label: 'Заголовок', fallback: 'Земля — первый ресурс системы.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'LSS (Land Search Service) — интеллектуальный модуль поиска земельных возможностей. Он работает на базе ИИ АО КСИ и помогает находить участки, анализировать локации, выявлять потенциал территорий и находить собственников.' },
        { key: 'cap_1', label: 'Возможность #1', fallback: 'Анализ скрытых площадок' },
        { key: 'cap_1_desc', label: 'Возможность #1 — описание', fallback: 'Поиск незадействованных и недооценённых участков' },
        { key: 'cap_2', label: 'Возможность #2', fallback: 'Оценка локаций' },
        { key: 'cap_2_desc', label: 'Возможность #2 — описание', fallback: 'Инфраструктура, транспорт, перспективы развития территории' },
        { key: 'cap_3', label: 'Возможность #3', fallback: 'Анализ собственников' },
        { key: 'cap_3_desc', label: 'Возможность #3 — описание', fallback: 'Открытые данные о владельцах и обременениях' },
        { key: 'cap_4', label: 'Возможность #4', fallback: 'Первичный взгляд ИИ' },
        { key: 'cap_4_desc', label: 'Возможность #4 — описание', fallback: 'Быстрый ИИ-анализ переданного участка или запроса' },
      ]},
      { id: 'submit', title: 'Как передать участок', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Как участвовать' },
        { key: 'title', label: 'Заголовок', fallback: 'Передай участок — получи первичный взгляд.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'Если у тебя есть земельный участок или запрос на поиск — передай его в систему. ИИ АО КСИ проведёт первичный анализ: локация, потенциал, возможность использования в программах КриптоМетров. Результат — единица опыта и, при наличии основания, начисление КМ.' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Есть участок или запрос — передай в систему.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Передать объект' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/mining-kvartiry' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Про ИИ АО КСИ' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/ai-ksi' },
      ]},
    ],
  },
  // ─── ПРАВОВАЯ МОДЕЛЬ ──────────────────────────────────────────────────────
  {
    id: 'legal',
    title: 'Правовая модель',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/legal' },
        { key: 'seo_title', label: 'SEO title', fallback: 'Правовая модель КриптоМетров' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'КМ — внутренняя единица учёта. Не ценная бумага, не криптовалюта, не гарантия доходности.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Правовая основа' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Правовая' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'модель.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'КМ — внутренняя единица учёта вклада участника. Не криптовалюта, не ценная бумага, не договор долевого участия. Проект создаётся поэтапно.' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Кооперативная модель' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/cooperative' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'FAQ' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'km_status', title: 'Статус КМ', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '01 · Что такое КМ с правовой точки зрения' },
        { key: 'title', label: 'Заголовок', fallback: 'Единица учёта. Не финансовый инструмент.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'КриптоМетр (КМ) является внутренней единицей учёта вклада участника в развитие системы КриптоМетры. КМ не является публичной криптовалютой, ценной бумагой, долговым инструментом или гарантированным инвестиционным продуктом. КМ не торгуется на биржах и не предполагает обязательного выкупа.' },
        { key: 'pt_1', label: 'Пункт #1', fallback: 'Не является криптовалютой или токеном' },
        { key: 'pt_2', label: 'Пункт #2', fallback: 'Не является ценной бумагой' },
        { key: 'pt_3', label: 'Пункт #3', fallback: 'Не гарантирует доходность или выкуп' },
        { key: 'pt_4', label: 'Пункт #4', fallback: 'Не является договором долевого участия' },
        { key: 'pt_5', label: 'Пункт #5', fallback: 'Не является покупкой квартиры или доли в объекте' },
      ]},
      { id: 'rules', title: 'Правила начисления', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '02 · Правила' },
        { key: 'title', label: 'Заголовок', fallback: 'Внутренние документы системы.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'Правила начисления, использования и учёта КМ определяются внутренними документами АО КСИ и кооператива. Документы публикуются по мере формирования правовой структуры проекта. Участие в системе означает согласие с действующими на момент участия правилами.' },
      ]},
      { id: 'stage', title: 'Этап создания', fields: [
        { key: 'kicker', label: 'Надзаголовок', fallback: '03 · Текущий статус' },
        { key: 'title', label: 'Заголовок', fallback: 'Проект в стадии создания.' },
        { key: 'text', label: 'Текст', multiline: true, fallback: 'Проект КриптоМетры находится в стадии поэтапного создания и запуска. Правовая структура кооператива формируется. Некоторые функции, описанные на сайте, являются перспективными и ещё не введены в эксплуатацию. Участие на текущем этапе означает вступление в создаваемую систему на ранней стадии.' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Есть вопросы по правовой части?' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Частые вопросы (FAQ)' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/faq' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Кооперативная модель' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/cooperative' },
      ]},
    ],
  },
  // ─── FAQ ──────────────────────────────────────────────────────────────────
  {
    id: 'faq',
    title: 'FAQ — Частые вопросы',
    sections: [
      { id: 'meta', title: 'SEO и настройки', fields: [
        { key: 'slug', label: 'URL', fallback: '/faq' },
        { key: 'seo_title', label: 'SEO title', fallback: 'FAQ — Частые вопросы о КриптоМетрах' },
        { key: 'seo_desc', label: 'SEO description', multiline: true, fallback: 'Ответы на самые частые вопросы об участии, КМ, ИИ, фонде и правовой модели.' },
        { key: 'published', label: 'Статус (published / draft)', fallback: 'published' },
      ]},
      { id: 'hero', title: 'Обложка', fields: [
        { key: 'chip', label: 'Метка', fallback: 'КриптоМетры · Вопросы и ответы' },
        { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Частые' },
        { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'вопросы.' },
        { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Всё, что нужно знать перед участием в системе КриптоМетры.' },
        { key: 'bg_image', label: 'Фон обложки', type: 'image', fallback: '' },
      ]},
      { id: 'questions', title: 'Вопросы и ответы', fields: [
        { key: 'q1', label: 'Вопрос 1', fallback: 'Что такое КриптоМетры?' },
        { key: 'a1', label: 'Ответ 1', multiline: true, fallback: 'КриптоМетры — это медийно-кооперативная система распределённого девелопмента. Участники с помощью ИИ АО КСИ создают Виртуального девелопера и получают КМ за вклад в развитие системы.' },
        { key: 'q2', label: 'Вопрос 2', fallback: 'Что такое КМ (КриптоМетр)?' },
        { key: 'a2', label: 'Ответ 2', multiline: true, fallback: 'КМ — внутренняя единица учёта вклада участника. Её можно получить за денежный вклад, действия в системе (анкеты, запросы к ИИ, репосты) или привлечение участников. КМ не является криптовалютой или ценной бумагой.' },
        { key: 'q3', label: 'Вопрос 3', fallback: 'Как майнить КМ?' },
        { key: 'a3', label: 'Ответ 3', multiline: true, fallback: 'Майнинг — это любое участие в системе: регистрация, заполнение анкеты квартиры, отправка запросов к ИИ, репосты, приглашение участников, передача объектов. Каждое действие верифицируется и создаёт единицу опыта.' },
        { key: 'q4', label: 'Вопрос 4', fallback: 'Можно ли майнить без денег?' },
        { key: 'a4', label: 'Ответ 4', multiline: true, fallback: 'Да. Трудовой вклад — анкеты, запросы, репосты, приглашения — тоже конвертируется в КМ. Денежный вклад даёт больше КМ, но не является обязательным условием участия.' },
        { key: 'q5', label: 'Вопрос 5', fallback: 'Что делает ИИ в системе?' },
        { key: 'a5', label: 'Ответ 5', multiline: true, fallback: 'ИИ АО КСИ классифицирует запросы участников, маршрутизирует их к облачным моделям или операторам, структурирует результаты и пополняет базу знаний. Каждый запрос создаёт единицу опыта в реестре.' },
        { key: 'q6', label: 'Вопрос 6', fallback: 'Что делает АО КСИ?' },
        { key: 'a6', label: 'Ответ 6', multiline: true, fallback: 'АО «КриптоСтройИнвест» — управляющая компания и технологический оператор проекта. Создаёт и обслуживает ИИ-контур, медиаплатформу, реестры, операционный контур и партнёрские программы.' },
        { key: 'q7', label: 'Вопрос 7', fallback: 'Что делает кооператив?' },
        { key: 'a7', label: 'Ответ 7', multiline: true, fallback: 'Кооператив — юридическая форма объединения участников. Он не продаёт квартиры и не является ДДУ. В будущем кооператив может запускать отдельные целевые программы, связанные с недвижимостью.' },
        { key: 'q8', label: 'Вопрос 8', fallback: 'Что такое Фонд КриптоМетров?' },
        { key: 'a8', label: 'Ответ 8', multiline: true, fallback: 'Фонд — денежная база проекта. Формируется из взносов участников, рекламных доходов медиаплатформы (до 50%) и партнёрских поступлений.' },
        { key: 'q9', label: 'Вопрос 9', fallback: 'Что такое расчётная обеспеченность КМ?' },
        { key: 'a9', label: 'Ответ 9', multiline: true, fallback: 'Расчётная обеспеченность = размер фонда / количество КМ в обращении. Это ориентировочный показатель, который может меняться. Он не является обещанием доходности или гарантией выкупа.' },
        { key: 'q10', label: 'Вопрос 10', fallback: 'Можно ли купить квартиру за КМ?' },
        { key: 'a10', label: 'Ответ 10', multiline: true, fallback: 'На текущем этапе — нет. КМ фиксирует участие в создании системы. В будущем кооператив может запустить целевые программы, в которых КМ могут учитываться как вклад. Подробности — по мере формирования правовой структуры.' },
        { key: 'q11', label: 'Вопрос 11', fallback: 'Какие есть риски?' },
        { key: 'a11', label: 'Ответ 11', multiline: true, fallback: 'Проект находится в стадии создания. Функции и параметры системы могут меняться. КМ не имеет гарантированной стоимости и не торгуется на биржах. Участие — это вклад в создание системы, а не инвестиционный продукт.' },
        { key: 'q12', label: 'Вопрос 12', fallback: 'Когда появится блокчейн?' },
        { key: 'a12', label: 'Ответ 12', multiline: true, fallback: 'Блокчейн-слой — перспективный этап развития реестров. Сначала будет реализована hash-фиксация каждой единицы опыта и записи в реестре КМ. Сроки определятся после стабилизации основной системы.' },
        { key: 'q13', label: 'Вопрос 13', fallback: 'Как стать участником?' },
        { key: 'a13', label: 'Ответ 13', multiline: true, fallback: 'Зарегистрируйся на сайте, заполни анкету квартиры или отправь первый запрос к ИИ. Это занимает несколько минут и сразу даёт первые КМ.' },
      ]},
      { id: 'cta', title: 'Финальный призыв', fields: [
        { key: 'title', label: 'Заголовок CTA', fallback: 'Не нашёл ответ на свой вопрос?' },
        { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Задать вопрос ИИ' },
        { key: 'cta_primary_url', label: 'Ссылка', fallback: '/how-ai' },
        { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Получить КМ' },
        { key: 'cta_secondary_url', label: 'Ссылка вторичная', fallback: '/mining-kvartiry' },
      ]},
    ],
  },
];

export const CONTENT_SCHEMA: ContentPage[] = [
  {
    id: 'index',
    title: 'Главная страница',
    sections: [
      {
        id: 'hero',
        title: 'Обложка (Hero)',
        fields: [
          { key: 'chip', label: 'Метка над заголовком', fallback: 'Майнинг метров · Запуск · Май 2026' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Майним' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'недвижимость' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Архитектурная платформа для тех, кто устал переплачивать — и решил строить по уму. Входи в систему' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Что это такое' },
          { key: 'stat_1_label', label: 'Статистика #1 — подпись', fallback: 'ниже рынка' },
          { key: 'stat_2_label', label: 'Статистика #2 — подпись', fallback: 'деньги на ладони' },
          { key: 'stat_3_label', label: 'Статистика #3 — подпись', fallback: 'рассрочка 20 лет' },
          { key: 'stat_4_label', label: 'Статистика #4 — подпись', fallback: 'аккредитованы' },
        ],
      },
      {
        id: 'idea',
        title: 'Манифест / Идея',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Манифест · 01' },
          { key: 'desc', label: 'Описание справа от заголовка', multiline: true, fallback: 'Ты платишь не только за бетон и стены. В цену зашиты чужие кредиты, реклама, риски и жирная наценка. КриптоМетры разворачивают логику — не покупать в конце по полной. А входить раньше.' },
        ],
      },
      {
        id: 'system',
        title: 'Архитектура системы',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Архитектура системы · 03' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Как по-старинке.' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'Только с технологиями.' },
          { key: 'desc', label: 'Описание', multiline: true, fallback: 'Земля, профессиональный девелопер, прозрачные финансы и люди, которые заказывают — а не покупают. Четыре элемента, связанные в единый контур.' },
        ],
      },
      {
        id: 'you',
        title: 'Ключевая идея (Вы — заказчик)',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Ключевая идея · 02' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Вы не дольщик.' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'Вы — заказчик.' },
        ],
      },
      {
        id: 'money',
        title: 'Финансы / Без ипотеки',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Финансы · 07' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Без ипотечной' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'кабалы.' },
          { key: 'desc', label: 'Описание', multiline: true, fallback: 'Вместо банковской удавки — своя логика. Инструменты, которые работают на участника, а не на чужой процент.' },
          { key: 'tool_1_label', label: 'Инструмент #1', fallback: 'Рассрочка' },
          { key: 'tool_1_desc', label: 'Инструмент #1 — описание', fallback: 'Беспроцентная до 20 лет' },
          { key: 'tool_2_label', label: 'Инструмент #2', fallback: 'Накопительная' },
          { key: 'tool_2_desc', label: 'Инструмент #2 — описание', fallback: 'Программа без переплат' },
          { key: 'tool_3_label', label: 'Инструмент #3', fallback: 'Субсидии' },
          { key: 'tool_3_desc', label: 'Инструмент #3 — описание', fallback: 'Коммерческие от партнёров' },
          { key: 'tool_4_label', label: 'Инструмент #4', fallback: 'Криптотека' },
          { key: 'tool_4_desc', label: 'Инструмент #4 — описание', fallback: 'Новый инструмент входа' },
        ],
      },
      {
        id: 'mining',
        title: 'Майнинг квартиры (блок на главной)',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Программа участия · Новый раздел' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Перейти на страницу майнинга' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Начать майнить' },
        ],
      },
      {
        id: 'accreditation',
        title: 'Отбор застройщиков',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Отбор · 06' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Строят только те,' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'кто прошёл отбор.' },
          { key: 'desc', label: 'Описание', multiline: true, fallback: 'В систему допускаются только аккредитованные девелоперы и подрядчики с репутацией.' },
          { key: 'criteria_1', label: 'Критерий #1', fallback: 'Опыт и объекты' },
          { key: 'criteria_2', label: 'Критерий #2', fallback: 'Репутация' },
          { key: 'criteria_3', label: 'Критерий #3', fallback: 'Прозрачные сметы' },
          { key: 'criteria_4', label: 'Критерий #4', fallback: 'Открытый контур' },
          { key: 'criteria_5', label: 'Критерий #5', fallback: 'Цифровой контроль' },
          { key: 'criteria_6', label: 'Критерий #6', fallback: 'Ответственность' },
        ],
      },
      {
        id: 'how',
        title: 'Как это работает',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Как это работает · 08' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Шесть шагов' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'к своему жилью.' },
          { key: 'desc', label: 'Описание', multiline: true, fallback: 'Скидываемся. Покупаем землю. Нанимаем девелопера. Контролируем стройку. Принимаем результат. Живём.' },
        ],
      },
      {
        id: 'cta',
        title: 'Финальный призыв',
        fields: [
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Войди в систему' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'раньше рынка.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Получить КМ' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Написать нам' },
        ],
      },
      {
        id: 'images',
        title: 'Изображения',
        fields: [
          { key: 'logo', label: 'Логотип в шапке', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/bucket/e42b3898-d2ef-44ff-b94f-465207ab3b2c.png' },
          { key: 'hero', label: 'Фон обложки (Hero)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/bucket/b8c94214-dc0f-4d12-b0b0-4235830f89d7.png' },
          { key: 'resort', label: 'Курорт / посёлок (блок «Манифест»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/8fbb118f-f75d-4354-bd66-00ab3e981d81.jpg' },
          { key: 'quarter', label: 'Жилой квартал (блок «Архитектура»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/e3be1098-9720-4721-b8b8-f18dbefc328c.jpg' },
          { key: 'facade', label: 'Фасад дома (блок «Вы — заказчик»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/275e2561-0665-4b11-a4fd-cd25607e8026.jpg' },
          { key: 'courtyard', label: 'Двор (блок «Финансы»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/b93a50ee-e6ce-45db-94d9-0897ae028c7b.jpg' },
          { key: 'aerial', label: 'Аэрофото (блок «Майнинг»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/d4c1c38f-bf46-4eb1-a5a1-9e0187887e75.jpg' },
          { key: 'interior', label: 'Интерьер (блок «Как работает»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/f1e60bd7-338c-4fc2-92c1-22c9c49a1025.jpg' },
          { key: 'village', label: 'Деревня (блок «Отбор»)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/ff379895-1c9b-4d90-a62a-f4abcc281fe2.jpg' },
          { key: 'site', label: 'Стройплощадка (FAQ / Финал)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/b7c8f3e7-b3ae-4074-baf6-76e997048aef.jpg' },
        ],
      },
    ],
  },
  {
    id: 'mining',
    title: 'Страница «Майнинг квартиры»',
    sections: [
      {
        id: 'hero',
        title: 'Обложка (Hero)',
        fields: [
          { key: 'chip', label: 'Метка над заголовком', fallback: 'Экосистема КриптоМетр · Программа участия' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Майнинг' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'квартиры' },
          { key: 'subtitle', label: 'Подзаголовок', multiline: true, fallback: 'Майни свой путь к будущему жилью уже сегодня. Участие, задания, фидбек — всё это конвертируется в КМ и двигает тебя к цели.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Начать майнить' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Заполнить анкету квартиры' },
        ],
      },
      {
        id: 'how',
        title: 'Как это работает',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Как это работает · 01' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Три шага —' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'одна система.' },
        ],
      },
      {
        id: 'tasks',
        title: 'Начисления (задания)',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Начисления · 03' },
          { key: 'task_1_label', label: 'Задание #1', fallback: 'Регистрация' },
          { key: 'task_1_value', label: 'Задание #1 — значение', fallback: 'до 0,10 КМ' },
          { key: 'task_2_label', label: 'Задание #2', fallback: 'Подробная анкета' },
          { key: 'task_2_value', label: 'Задание #2 — значение', fallback: 'до 0,25 КМ' },
          { key: 'task_3_label', label: 'Задание #3', fallback: 'Полный диалог с системой' },
          { key: 'task_3_value', label: 'Задание #3 — значение', fallback: 'до 0,25 КМ' },
          { key: 'task_4_label', label: 'Задание #4', fallback: 'Подписка на канал' },
          { key: 'task_4_value', label: 'Задание #4 — значение', fallback: '0,01 КМ' },
          { key: 'cta_primary', label: 'Кнопка под начислениями', fallback: 'Заполнить анкету квартиры' },
        ],
      },
      {
        id: 'levels',
        title: 'Уровни пути',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'Уровни пути · 05' },
          { key: 'level_1_name', label: 'Уровень #1', fallback: 'Старт' },
          { key: 'level_1_desc', label: 'Уровень #1 — описание', fallback: 'Первые шаги в системе' },
          { key: 'level_2_name', label: 'Уровень #2', fallback: 'Профиль спроса' },
          { key: 'level_2_desc', label: 'Уровень #2 — описание', fallback: 'Система узнаёт тебя' },
          { key: 'level_3_name', label: 'Уровень #3', fallback: 'Подтверждённый участник' },
          { key: 'level_3_desc', label: 'Уровень #3 — описание', fallback: 'Твой вклад виден' },
          { key: 'level_4_name', label: 'Уровень #4', fallback: 'Ядро спроса' },
          { key: 'level_4_desc', label: 'Уровень #4 — описание', fallback: 'Формируешь будущие проекты' },
          { key: 'level_5_name', label: 'Уровень #5', fallback: 'Следующий контур' },
          { key: 'level_5_desc', label: 'Уровень #5 — описание', fallback: 'Право перейти дальше' },
        ],
      },
      {
        id: 'contour',
        title: 'Следующий контур (после 100 КМ)',
        fields: [
          { key: 'kicker', label: 'Надзаголовок', fallback: 'После 100 КМ · 06' },
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Переход' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'на следующий контур.' },
          { key: 'rule', label: 'Главное правило', multiline: true, fallback: 'Каждый намайненный КМ открывает право внести до 1 КМ целевого взноса.' },
        ],
      },
      {
        id: 'final',
        title: 'Финальный призыв',
        fields: [
          { key: 'title_1', label: 'Заголовок — строка 1', fallback: 'Начните майнить' },
          { key: 'title_2', label: 'Заголовок — строка 2 (акцент)', fallback: 'свою квартиру' },
          { key: 'title_3', label: 'Заголовок — строка 3', fallback: 'уже сегодня.' },
          { key: 'cta_primary', label: 'Кнопка — главная', fallback: 'Начать майнить' },
          { key: 'cta_secondary', label: 'Кнопка — вторичная', fallback: 'Заполнить анкету квартиры' },
        ],
      },
      {
        id: 'images',
        title: 'Изображения',
        fields: [
          { key: 'hero_bg', label: 'Фон обложки (Hero)', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/d4c1c38f-bf46-4eb1-a5a1-9e0187887e75.jpg' },
          { key: 'side_bg', label: 'Фон секции «После 100 КМ»', type: 'image', fallback: 'https://cdn.poehali.dev/projects/b7c1e63c-11b6-4625-a266-770a5b28551a/files/f1e60bd7-338c-4fc2-92c1-22c9c49a1025.jpg' },
        ],
      },
    ],
  },
];